import Head from "next/head";
import { useState } from 'react';
import GradientButton from "./components/GradientButton";
import HighlightedText from "./components/HighlightedText";
import type { Color } from "./components/colorConfig";
import { colorConfig, gradients } from "./components/colorConfig";

export default function Home() {

  const colors: Color[] = Object.keys(colorConfig) as Color[];
  const [selectedGradient, setSelectedGradient] = useState(gradients.amber);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="max-w-md text-stone-900">
            Somehow we realize that great stories are
            told in conflict, but we are unwilling to
            embrace the potential greatness of the story
            we are actually in. {" "}
            <HighlightedText selectedGradient={selectedGradient}>
              We think God is unjust, rather than a master storyteller.
            </HighlightedText>
            <br />
            <br />
            - Donald Miller
          </div>
          <div className="flex space-x-4">
            {colors.map(color => (
              <GradientButton
                key={color}
                color={color}
                selectedGradient={selectedGradient}
                setSelectedGradient={setSelectedGradient}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
